name: Build Ionic App and Deploy on FTP

on: [push]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master 
        
      - name: Install Angular
        run: npm install -g @angular/cli@latest

      - name: Install Ionic
        run: npm install -g @ionic/cli
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: ng build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: sha.ewarenet.com
          username: up@sha.ewarenet.com	
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: www/
